inherit_from: ".rubocop_todo.yml"

require:
  - "rubocop-gitlab-security"
  - "rubocop-performance"
  - "rubocop-rspec"

AllCops:
  Exclude:
    - "bin/**/*"
    - "spec/db/**/*"
    - "vendor/**/*"
  NewCops: "enable"
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: "double_quotes"

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
