source "https://rubygems.org"

gemspec

gem "actionpack"
gem "debug"
gem "fuubar"
gem "guard"
gem "guard-rspec"
gem "guard-rubocop"
gem "rake"
gem "rspec"
gem "rspec-collection_matchers"
gem "rubocop"
gem "rubocop-gitlab-security"
gem "rubocop-performance"
gem "rubocop-rspec"
gem "simplecov"
gem "sqlite3"
gem "syntax_suggest"
gem "wisper-rspec"
